### ISSUE TITLE
Extend obsoletion action to allow replaced_by and support OBO merge semantics

### ISSUE THREAD

**Issue by cmungall** [balhoff/obo-actions#1]
The obsolete action current adds the `owl:deprecated` axiom and removes logical axioms, as well as label prefixing to get around the protege rendering bug, all good.

We would also like a way to easily add `consider` or `replaced_by` annotations. This is not too painful in the annotation editor, but OE users are used to doing this with a drag. No idea how easy this...

Another useful feature would be support OBO merge semantics. This means adding an annotation

```
obo:IAO_0000231=obo:IAO_0000227
```

i.e. 'has obsolescence reason' = 'terms merged'

to the class. In combination with a replaced_by, this will generate an alt_id in OBOF, as specced here:
https://github.com/owlcs/owlapi/issues/317#issuecomment-67412550

This may be best served by a different action, "Obsolete term for merge" that adds the merge annotation, but leaves it to the user to specify replaced_by?

@balhoff sorry to invade your github repo, we're not presupposing you will do this, I just wanted a place to track this, and your plugin seems the best start

**Comment by balhoff** [comment]
No problem, would be great to expand this tool.

**Comment by cmungall** [comment]
This issue was moved to owlcollab/protege-obo-plugin#7
